package com.hafnium.it.report

/**
 * Writes an observation's types as Kotlin declarations: each type with its supertypes and the declarations of the
 * called method, bases first. Constructor arguments and method bodies are shown as "…"; parameter names are not
 * recorded, so they are derived from their types.
 */
class KotlinDeclarations(
    /** Names in this package are written without it. */
    private val basePackage: String,
    /** The types in this package get an entry comment; others, e.g. a framework's interfaces, their package. */
    private val ownPackage: String,
    private val entries: ReceiverEntries?,
) {

    fun render(observation: Observation): String {
        val types = observation.types.filter { !it.name.startsWith("java.") }
        val byName = types.associateBy { it.name }
        val out = mutableListOf<String>()
        for (type in types.reversed()) {
            if (type.isEnumConstant) {
                continue // written inside its enum
            }
            val block = mutableListOf<String>()
            val own = type.name.startsWith("$ownPackage.")
            val packageName = type.name.substringBeforeLast('.', "")
            if (!own) {
                block += "// $packageName"
            } else if (packageName != basePackage && !type.isAnonymous) {
                block += "// in package ${short(packageName)}"
            }
            val supertypes = type.supertypes.map { s -> if (byName[s]?.isInterface == true) simpleName(s) else "${simpleName(s)}(…)" }
            val header = if (supertypes.isEmpty()) "" else " : " + supertypes.joinToString(", ")
            val body = methods(observation, type)
            val generated = if (type.isGenerated) " // generated at runtime" else ""
            when {
                type.kind == "enum" -> {
                    if (own) block += entryComment(type.name)
                    block += "enum class ${simpleName(type.name)} {"
                    val constants = types.filter { it.isEnumConstant && it.supertypes.firstOrNull() == type.name }
                    for (constant in constants) {
                        val constantBody = methods(observation, constant)
                        block += "    ${constant.name.substringAfterLast('$')} {" +
                            (if (constantBody.isEmpty()) " " else " " + constantBody.joinToString("; ") + " ") + "},"
                    }
                    if (constants.isNotEmpty()) block += "    ;"
                    block += body.map { "    $it" }
                    block += "}"
                }
                type.isAnonymous -> {
                    if (own) block += entryComment(type.name)
                    block += if (body.isEmpty()) "val anonymous = object$header {}" else "val anonymous = object$header {"
                    if (body.isNotEmpty()) {
                        block += body.map { "    $it" }
                        block += "}"
                    }
                }
                type.enclosing != null && own -> {
                    block += entryComment(type.enclosing)
                    block += "open class ${simpleName(type.enclosing)} {"
                    block += entryComment(type.name).map { "    $it" }
                    block += "    inner class ${type.name.substringAfterLast('$')}$header {"
                    block += body.map { "        $it" }
                    block += "    }"
                    block += "}"
                }
                else -> {
                    if (own) block += entryComment(type.name)
                    if (body.isEmpty()) {
                        block += "${type.kind} ${simpleName(type.name)}$header$generated"
                    } else {
                        block += "${type.kind} ${simpleName(type.name)}$header {$generated"
                        block += body.map { "    $it" }
                        block += "}"
                    }
                }
            }
            out += block
            out += ""
        }
        out += observation.call
        return out.joinToString("\n")
    }

    private fun methods(observation: Observation, type: TypeInfo): List<String> {
        val declarations = observation.declarations
        return declarations.withIndex().filter { it.value.owner == type.name }.map { (i, d) ->
            val overrides = declarations.drop(i + 1).any { it.name == d.name && it.owner != d.owner && "bridge" !in it.modifiers }
            val signature = "fun ${d.name}(${parameters(d.parameterTypes)})"
            when {
                "bridge" in d.modifiers -> "// bridge generated by the compiler: $signature"
                "abstract" in d.modifiers -> "abstract $signature"
                else -> {
                    val final = "final" in d.modifiers
                    val modifiers = when {
                        overrides -> if (final) "final override " else "override "
                        !final && !type.isInterface -> "open "
                        else -> ""
                    }
                    "$modifiers$signature { … }"
                }
            }
        }
    }

    private fun parameters(types: List<String>) = types.joinToString(", ") { type ->
        if (type == "Object") "item: Any?" else type.replaceFirstChar { it.lowercase() } + ": " + type
    }

    private fun entryComment(className: String): List<String> {
        if (entries == null) return emptyList()
        val matching = entries.matching(className)
        if (matching.isEmpty()) return listOf("// no [augment.receiver] entry")
        val deciding = matching.first()
        val others = matching.drop(1)
        return listOf(
            "// [augment.receiver] \"${short(deciding.key)}\" = \"${deciding.value}\"" +
                if (others.isEmpty()) "" else ", wins over " + others.joinToString(", ") { "\"${short(it.key)}\" = \"${it.value}\"" },
        )
    }

    private fun short(name: String) = name.removePrefix("$basePackage.")

    private fun simpleName(name: String): String {
        val simple = name.substringAfterLast('.')
        return if (simple.any { it == '$' || it == ' ' }) "`$simple`" else simple
    }
}
